#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2023/11/14 17:46
# @Author  : Cl0udG0d
# @File    : constants.py
# @Github: https://github.com/Cl0udG0d

# 仲裁ID
DOS_ID = 0
STABLE_DIRTY_ID1 = 1
STABLE_DIRTY_ID2 = 4
STABLE_DIRTY_ID3 = 8
DEFAULT_SIGNAL_ID = 392
DEFAULT_DOOR_ID = 411
DEFAULT_SPEED_ID = 580


# DATA
CAN_DOOR_LOCK = 0
CAN_DOOR1_LOCK = 1
CAN_DOOR2_LOCK = 2
CAN_DOOR3_LOCK = 3
CAN_DOOR4_LOCK = 4
CAN_DOOR_UNLOCK = 5
CAN_DOOR1_UNLOCK = 6
CAN_DOOR2_UNLOCK = 7
CAN_DOOR3_UNLOCK = 8
CAN_DOOR4_UNLOCK = 9
MAX_SPEED = 180
MIN_SPEED = 0
CAN_LEFT_SIGNAL = 1
CAN_RIGHT_SIGNAL = 2
ON = 1
OFF = 0

# POS
DEFAULT_DOOR_POS = 2
DEFAULT_SIGNAL_POS = 0
DEFAULT_SPEED_POS = 3
STABLE_DIRTY_POS1 = 1
STABLE_DIRTY_POS2 = 4
STABLE_DIRTY_POS3 = 6

